version: '3'

tasks:
  default:
    aliases:
      - list
    desc: List all tasks
    cmd: task -l
  ruff:
    desc: Run ruff
    cmds:
      - ruff check --fix
      - ruff format
    silent: true
  type-check:
    desc: Check type by pyright
    cmds:
      - uv tool run pyright
    silent: true
  push:
    desc: git push
    cmds:
      - git add .
      - git commit
      - git push origin $(git rev-parse --abbrev-ref HEAD)
    silent: false
  pull:
    desc: git pull
    cmd: git pull origin $(git rev-parse --abbrev-ref HEAD)
    silent: false

